# Auto-generated explicit list of the ACTIVE PSP engine translation units.
# This is the migrated dependency-closure compile set (see MIGRATION.md). No wildcards:
# every file here was reached by following the PSP entry point's dependency graph.
# Excluded by design (kept as non-compiled architecture / stubs): other-platform backends,
# OpenAL audio impl, AngelScript scripting, ENet/ixwebsocket multiplayer transport, ImGui.
#
# The original-JJ2 converters are compiled into the EBOOT so a PSP can create its own cache when only the
# original game files are installed. Tools/psp-bake uses this exact conversion code on the host as well.

set(PSP_ENGINE_SOURCES
	${NEXT_SOURCE_DIR}/Dependencies/jsoncpp/reader.cpp
	${NEXT_SOURCE_DIR}/Dependencies/jsoncpp/value.cpp
	${NEXT_SOURCE_DIR}/Dependencies/jsoncpp/writer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/ActorBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/AmmoCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/CarrotCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/CarrotFlyCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/CarrotInvincibleCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/CoinCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/CollectibleBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/FastFireCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/FoodCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/GemCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/GemGiant.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/GemRing.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/OneUpCollectible.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Collectibles/Stopwatch.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bat.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bee.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/Bilsy.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/Bolly.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/BossBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/Bubba.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/Devan.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/DevanRemote.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/Queen.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/Robot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/TurtleBoss.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Bosses/Uterus.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Caterpillar.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Crab.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Demon.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Doggy.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Dragon.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Dragonfly.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/EnemyBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/FatChick.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Fencer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Fish.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Helmut.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/LabRat.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Lizard.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/LizardFloat.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/MadderHatter.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Monkey.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Rapier.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Raven.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Skeleton.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Sparks.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Sucker.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/SuckerFloat.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Turtle.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/TurtleShell.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/TurtleTough.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/TurtleTube.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Enemies/Witch.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/AirboardGenerator.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/AmbientBubbles.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/AmbientSound.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/Bird.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/BirdCage.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/Bomb.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/BonusWarp.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/Checkpoint.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/Copter.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/EndOfLevel.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/Eva.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/IceBlock.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/Moth.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/RollingRock.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/Spring.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/SteamNote.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Environment/SwingingVine.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Explosion.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Lighting/FlickerLight.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Lighting/PulsatingRadialLight.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Lighting/StaticRadialLight.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/CtfBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/Flag.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/LocalPlayerOnServer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/MpPlayer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/PlayerOnServer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/RemotablePlayer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/RemoteActor.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Multiplayer/RemotePlayerOnServer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Player.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/PlayerCorpse.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/AmmoBarrel.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/AmmoCrate.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/BarrelContainer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/Bridge.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/CrateContainer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/GemBarrel.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/GemCrate.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/GenericContainer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/MovingPlatform.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/PinballBumper.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/PinballPaddle.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/Pole.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/PowerUpMorphMonitor.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/PowerUpShieldMonitor.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/PowerUpWeaponMonitor.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/PushableBox.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/SpikeBall.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Solid/TriggerCrate.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/SolidObjectBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/BlasterShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/BouncerShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/ElectroShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/FreezerShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/PepperShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/RFShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/SeekerShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/ShieldFireShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/ShieldLightningShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/ShieldWaterShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/ShotBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/TNT.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/Thunderbolt.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Actors/Weapons/ToasterShot.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Collisions/DynamicTree.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Collisions/DynamicTreeBroadPhase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/AnimSetMapping.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/EventConverter.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/JJ2Anims.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/JJ2Block.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/JJ2Data.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/JJ2Episode.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/JJ2Level.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/JJ2Strings.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Compatibility/JJ2Tileset.cpp
	${NEXT_SOURCE_DIR}/Jazz2/ContentResolver.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Events/EventMap.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Events/EventSpawner.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Input/ControlScheme.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Input/RgbLights.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Input/RumbleProcessor.cpp
	${NEXT_SOURCE_DIR}/Jazz2/LevelHandler.cpp
	${NEXT_SOURCE_DIR}/Jazz2/LevelInitialization.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/ConnectionResult.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/GameModes/BattleMode.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/GameModes/CaptureTheFlagMode.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/GameModes/CooperationMode.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/GameModes/GameModeFactory.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/GameModes/RaceMode.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/GameModes/TeamBattleMode.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/GameModes/TreasureHuntMode.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/MpLevelHandler.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/NetworkManager.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/NetworkManagerBase.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/Peer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Multiplayer/RaceRouteGenerator.cpp
	${NEXT_SOURCE_DIR}/Jazz2/PreferencesCache.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Rendering/BlurRenderPass.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Rendering/CombineRenderer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Rendering/LightingRenderer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Rendering/PlayerViewport.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Rendering/UpscaleRenderPass.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Resources.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Tiles/TileMap.cpp
	${NEXT_SOURCE_DIR}/Jazz2/Tiles/TileSet.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/Canvas.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/Font.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/FormattedTextBlock.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/HUD.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/InGameConsole.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/Multiplayer/MpHUD.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/Multiplayer/MpInGameCanvasLayer.cpp
	${NEXT_SOURCE_DIR}/Jazz2/UI/Multiplayer/MpInGameLobby.cpp
	${NEXT_SOURCE_DIR}/Shared/Base/Format.cpp
	${NEXT_SOURCE_DIR}/Shared/Containers/DateTime.cpp
	${NEXT_SOURCE_DIR}/Shared/Containers/SmallVector.cpp
	${NEXT_SOURCE_DIR}/Shared/Containers/String.cpp
	${NEXT_SOURCE_DIR}/Shared/Containers/StringUtils.cpp
	${NEXT_SOURCE_DIR}/Shared/Containers/StringView.cpp
	${NEXT_SOURCE_DIR}/Shared/Core/Logger.cpp
	${NEXT_SOURCE_DIR}/Shared/Cryptography/xxHash.cpp
	${NEXT_SOURCE_DIR}/Shared/Environment.cpp
	${NEXT_SOURCE_DIR}/Shared/IO/BoundedFileStream.cpp
	${NEXT_SOURCE_DIR}/Shared/IO/Compression/DeflateStream.cpp
	${NEXT_SOURCE_DIR}/Shared/IO/FileStream.cpp
	${NEXT_SOURCE_DIR}/Shared/IO/FileSystem.cpp
	${NEXT_SOURCE_DIR}/Shared/IO/MemoryStream.cpp
	${NEXT_SOURCE_DIR}/Shared/IO/PakFile.cpp
	${NEXT_SOURCE_DIR}/Shared/IO/Stream.cpp
	${NEXT_SOURCE_DIR}/Shared/Utf8.cpp
	${NEXT_SOURCE_DIR}/nCine/AppConfiguration.cpp
	${NEXT_SOURCE_DIR}/nCine/Application.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/Algorithms.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/BitArray.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/Clock.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/FrameTimer.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/HashFunctions.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/Object.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/Random.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/TimeStamp.cpp
	${NEXT_SOURCE_DIR}/nCine/Base/Timer.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/AnimatedSprite.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/BaseSprite.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/BinaryShaderCache.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Camera.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/DrawableNode.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLAttribute.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLBlending.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLBufferObject.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLClearColor.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLCullFace.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLDebug.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLDepthTest.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLFramebuffer.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLRenderbuffer.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLScissorTest.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLShader.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLShaderProgram.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLShaderUniformBlocks.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLShaderUniforms.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLTexture.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLUniform.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLUniformBlock.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLUniformBlockCache.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLUniformCache.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLVertexArrayObject.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLVertexFormat.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GL/GLViewport.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Geometry.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/GfxCapabilities.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/IGfxDevice.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/ITextureLoader.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Material.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/MeshSprite.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Particle.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/ParticleAffectors.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/ParticleInitializer.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/ParticleSystem.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RectAnimation.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderBatcher.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderBuffersManager.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderCommand.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderCommandPool.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderQueue.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderResources.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderStatistics.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/RenderVaoPool.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/SceneNode.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/ScreenViewport.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Shader.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/ShaderState.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Sprite.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Texture.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/TextureFormat.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/TextureLoaderPng.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/TextureLoaderRaw.cpp
	${NEXT_SOURCE_DIR}/nCine/Graphics/Viewport.cpp
	${NEXT_SOURCE_DIR}/nCine/I18n.cpp
	${NEXT_SOURCE_DIR}/nCine/Input/IInputManager.cpp
	${NEXT_SOURCE_DIR}/nCine/Input/JoyMapping.cpp
	${NEXT_SOURCE_DIR}/nCine/Primitives/Color.cpp
	${NEXT_SOURCE_DIR}/nCine/Primitives/Colorf.cpp
	${NEXT_SOURCE_DIR}/nCine/Primitives/Half.cpp
	${NEXT_SOURCE_DIR}/nCine/ServiceLocator.cpp
	${NEXT_SOURCE_DIR}/nCine/Threading/Thread.cpp
)
